FROM debian:latest as builder
ENV PATH "$PATH:/root/.cargo/bin"
WORKDIR /app
RUN apt-get -y update &&\
    apt-get install -y git curl gcc &&\
    curl https://sh.rustup.rs -sSf | sh -s -- -y &&\
    git clone https://github.com/HardhatChad/ore-cli.git &&\
    cd ore-cli &&\
    cargo build --release &&\
    mv ./target/release/ore /app

FROM debian:latest as prod
WORKDIR /app
COPY --from=0 /app/ore .
ENTRYPOINT /app/ore


