FROM debian:latest as builder
ENV PATH "$PATH:/root/.cargo/bin"
WORKDIR /app
RUN apt-get -y update &&\
    apt-get install -y git curl gcc &&\
    curl https://sh.rustup.rs -sSf | sh -s -- -y &&\
    git clone https://github.com/HardhatChad/ore-cli.git &&\
    cd ore-cli &&\
    sed -i 's/self.find_bus_id(treasury.reward_rate).await/Bus { id:5,rewards: 20000000}/g' src/mine.rs &&\
    sed -i 's/u32 = 3200/u32 = 100000/g' src/cu_limits.rs &&\
    cargo build --release &&\
    mv ./target/release/ore /app

FROM debian:latest as prod
WORKDIR /app
COPY --from=0 /app/ore .
ENTRYPOINT ["/app/ore","--keypair","/app/l.json"]


