apiVersion: apps/v1
kind: Deployment
metadata:
  name: ore-deployment
  labels:
    app: ore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ore
  template:
    metadata:
      labels:
        app: ore
    spec:
      containers:
      - name: ore
        image: axelharold/ore:main
        args: [ "--priority-fee" "500" "--keypair" "/config/l.json" "mine" "--threads" "2"]
        resources:
          limits:
            cpu: "4"
          requests:
            cpu: "2"
        volumesMounts:
        - name: lc
          mountPath: /config
      volumes:
      - name: lc
        configMap:
        # 提供包含要添加到容器中的文件的 ConfigMap 的名称
          name: l


